name: TestRemoveDummyToken

on:
  workflow_dispatch:

jobs:
  no-token-fails:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup Node with registry-url (no token provided)
        uses: Satishchoudhary94/setup-node@fix/oidc-support-1440
        with:
          node-version: '12'
          

      - name: Show .npmrc contents
        run: cat $NPM_CONFIG_USERCONFIG

      - name: npm install (this will fail without dummy token)
        run: npm install lodash --dry-run
    
