name: Test dummy token does not override user .npmrc

on:
  workflow_dispatch:

jobs:
  dummy-does-not-override:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Create user's project .npmrc with custom token
        run: |
          echo "//registry.npmjs.org/:_authToken=my_real_token_123" > .npmrc
          echo "registry=https://registry.npmjs.org/" >> .npmrc

      - name: Setup Node with registry-url 
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          

      - name: npm install 
        run: npm publish
        env:
            my_real_token_123: ${{ secrets.NPM_TOKEN }} # from users .npmrc

   
