name: Test dummy token does not override user .npmrc

on:
  workflow_dispatch:

jobs:
  dummy-does-not-override:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5


      - name: Setup Node with registry-url
        uses: actions/setup-node@v6
        with:
          node-version: "24"
        


      - name: npm publish
        run: npm publish

