name: TestRemoveDummyToken

on:
  workflow_dispatch:

jobs:
  no-token-fails:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup Node with registry-url (no token provided)
        uses: gowridurgad/setup-node@remove-dummy
        with:
          node-version: '14'
          registry-url: 'https://registry.npmjs.org'

      - name: Show .npmrc contents
        run: cat $NPM_CONFIG_USERCONFIG

      - name: npm install (this will fail without dummy token)
        run: npm install lodash --dry-run
